# This file will be executed in development environment, creating a
# database container.

services:
    web:
        command: npm run dev
        environment:
            - NODE_ENV=development
        volumes:
            - .:/app
        depends_on:
            monguito:
                condition: service_healthy
    monguito:
        healthcheck:
            test: 'mongosh'
            interval: 15s
            timeout: 10s
            retries: 3
            start_period: 15s
        image: mongo:latest
        # ports:
        #   - ${DB_PORT}:${DB_PORT}
        env_file:
            - .env
